from pathlib import Path
import pandas as pd
import numpy as np
from step4_alpha.model import build_baseline_score


# Project root = c2o-strategy/
# This makes file paths stable even if the script is run from another folder.
PROJECT_ROOT = Path(__file__).resolve().parents[1]

# Step 4 uses the output from Steps 1-3 as its input.
INPUT_PATH = PROJECT_ROOT / "outputs" / "panel_step3.parquet"
OUTPUT_PATH = PROJECT_ROOT / "outputs" / "alpha_scores.parquet"

def load_step3_panel() -> pd.DataFrame:
    """
    Load the Step 3 panel.

    This panel is generated by run_step2.py and already contains:
    - return variables: r_ON, r_ID, r_CC
    - lagged features: r_CC_lag1, r_ID_lag1, market_cap_lag1
    - universe filters: in_universe, eligible
    - borrow variables: dsi, dtcn, htb_tier, htb_flag
    """
    return pd.read_parquet(INPUT_PATH)


def build_targets(df: pd.DataFrame) -> pd.DataFrame:
    """
    Build Step 4 prediction targets.

    At decision time on date t, the strategy enters at Close_t and exits at Open_{t+1}.
    Therefore, the label for row t is the next day's overnight return r_ON_{t+1}.

    We keep three target columns:
    - target_raw: raw next overnight return
    - target_demeaned: cross-sectionally demeaned target, used as the main regression target
    - target_rank: daily cross-sectional percentile rank, useful for ranking evaluation
    """
    df = df.sort_values(["instrument_id", "date"]).copy()

    # Next overnight return: Close_t -> Open_{t+1}
    # This is allowed as a label, but must never be used as a feature.
    df["target_raw"] = df.groupby("instrument_id")["r_ON"].shift(-1)

    # Remove mean from the raw target
    df["target_raw_demeaned"] = (df["target_raw"]
                             - df.groupby("date")["target_raw"].transform("mean"))

    # Winsorize the target within each daily cross-section to reduce the impact of extreme moves.
    df["target_winsorized"] = (
        df.groupby("date")["target_raw"]
        .transform(lambda x: x.clip(x.quantile(0.01), x.quantile(0.99)))
    )

    # Main target: relative overnight performance versus the same-day cross-sectional average.
    # This matches the dollar-neutral long-short setting better than raw market-directional returns.
    df["target_winsorized_demeaned"] = (
        df["target_winsorized"]
        - df.groupby("date")["target_winsorized"].transform("mean")
    )

    # Optional ranking target: high value means the stock performed well relative to peers.
    df["target_rank"] = df.groupby("date")["target_raw"].rank(pct=True)

    return df

def build_features(df: pd.DataFrame) -> pd.DataFrame:
    """
    Build point-in-time alpha features.

    Conservative timing rule:
    features on date t should only use information available before the
    close auction decision on date t. For non-explicitly lagged variables,
    we apply an additional one-day shift within each stock.
    """
    df = df.sort_values(["instrument_id", "date"]).copy()

    # Return reversal / momentum features.
    # These are already lagged by the Step 1-3 pipeline, so they are safe to use.
    df["feat_r_cc_lag1"] = df["r_CC_lag1"]
    df["feat_r_id_lag1"] = df["r_ID_lag1"]

    # Volatility feature.
    # Apply one extra lag to avoid using any same-day information.
    df["feat_vol20_lag1"] = df.groupby("instrument_id")["vol20"].shift(1)

    # Liquidity feature.
    # Use log transform because ADV is highly skewed across stocks.
    df["adv20_lag1"] = df.groupby("instrument_id")["adv20"].shift(1)
    df["feat_log_adv20_lag1"] = np.log1p(df["adv20_lag1"])

    # Size feature.
    # market_cap_lag1 is already provided by Step 1-3.
    df["feat_log_mcap_lag1"] = np.log1p(df["market_cap_lag1"])

    # Short-interest / borrow features.
    # These are shifted again conservatively to make timing easy to defend.
    for col in ["dsi", "dtcn", "ddtcn", "htb_flag"]:
        if col in df.columns:
            df[f"feat_{col}_lag1"] = df.groupby("instrument_id")[col].shift(1)

    # Convert boolean HTB flag into numeric 0/1 feature.
    # False -> 0.0, True -> 1.0, missing values remain NaN.
    if "feat_htb_flag_lag1" in df.columns:
        df["feat_htb_flag_lag1"] = df["feat_htb_flag_lag1"].astype(float)


    return df

def standardize_features(df: pd.DataFrame, feature_cols: list[str]) -> tuple[pd.DataFrame, list[str]]:
    """
    Cross-sectionally standardize alpha features by date.

    For each trading date, each feature is transformed into a z-score across
    the eligible stocks on that date.

    This is suitable for a cross-sectional long-short strategy because the
    model ranks stocks relative to other tradable stocks on the same day.

    Missing or infinite z-scores are filled with 0.0, which represents a
    neutral cross-sectional feature value.
    """
    df = df.copy()
    z_cols = []

    for col in feature_cols:
        z_col = f"z_{col}"

        daily_mean = df.groupby("date")[col].transform("mean")
        daily_std = df.groupby("date")[col].transform("std")

        df[z_col] = (df[col] - daily_mean) / daily_std

        # Clean numerical issues from zero daily standard deviation or missing inputs.
        df[z_col] = df[z_col].replace([np.inf, -np.inf], np.nan)
        df[z_col] = df[z_col].fillna(0.0)

        z_cols.append(z_col)

    return df, z_cols


def build_alpha_dataset() -> tuple[pd.DataFrame, list[str]]:
    """
    Build Step 4 alpha dataset.

    Returns:
    - df: dataframe with targets, standardized features and baseline score
    - z_cols: standardized feature columns
    """
    df = load_step3_panel()

    # Step 4 alpha is constructed only on tradable stock-days.
    df = df[df["eligible"]].copy()

    df = build_targets(df)
    df = build_features(df)

    feature_cols = [
        "feat_r_cc_lag1",
        "feat_r_id_lag1",
        "feat_vol20_lag1",
        "feat_log_adv20_lag1",
        "feat_log_mcap_lag1",
        "feat_dsi_lag1",
        "feat_dtcn_lag1",
        "feat_ddtcn_lag1",
        "feat_htb_flag_lag1",
    ]
    feature_cols = [col for col in feature_cols if col in df.columns]

    df, z_cols = standardize_features(df, feature_cols)
    df = build_baseline_score(df)

    return df, z_cols


if __name__ == "__main__":
    df, z_cols = build_alpha_dataset()
    print(df.head())
    print(df.shape)
    print("Standardized features:", z_cols)